#!/bin/sh

scp tmp/router_3/chilli root@192.168.5.1:/etc/init.d/
scp tmp/router_3/config root@192.168.5.1:/etc/chilli
scp tmp/router_3/coova.html root@192.168.5.1:/etc/chilli/www
scp tmp/router_3/fon.png root@192.168.5.1:/etc/chilli/www

/etc/init.d/chilli enable
/etc/init.d/chilli start
