#!/bin/sh

echo "The following 4 password prompts are to move chilli files" 

scp tmp/router_3/chilli root@192.168.5.1:/etc/init.d/
scp tmp/router_3/config root@192.168.5.1:/etc/chilli
scp tmp/router_3/coova.html root@192.168.5.1:/etc/chilli/www
scp tmp/router_3/fon.png root@192.168.5.1:/etc/chilli/www

echo "Starting chilli and running self-destruct script..."
ssh root@192.168.5.1 "cd /etc/init.d; ./chilli enable; ./chilli start; chilli; ~/self_destruct; echo "Your Mac address is: "; ~/rid"

echo "Your MAC address is: "

