#!/usr/bin/expect
spawn "./pieces/telnet"
send_user "What port number are you using?"
stty -echo
expect_user -re "(.*)\n"
set port $expect_out(1,string)
stty echo

expect "step"
#while loop until laptop reboots and canenter.
#yes when prompted, no when not
spawn "./pieces/config $port"

expect ":"
send "yes"

#start next
