#!/usr/bin/expect
spawn telnet 192.168.1.1

#uci set wireless.@wifi-iface[0].mode='';
#uci commit;
#uci set wireless.@wifi-iface[''].ssid=''\r" 
send "
uci set network.lan.ipaddr=192.168.1.1
uci set wireless.radio0.disabled=0
\r"
send "
echo 'type in passwd and set the password. Then type in k'\r
"
interact -nobuffer -re "k\r" {
    return
}
expect "k"
send "
uci commit\r
reboot\r
"
expect eof
