#!/usr/bin/expect
spawn telnet 192.168.1.1

while 1{

    send "passwd\r"
    expect "assword:"

    stty -echo
    expect_user -re "(.*)\n"
    set password $expect_out(1,string)
    stty echo

    send -- "$password\r"

    expect "assword:"

    stty -echo
    expect_user -re "(.*)\n"
    set cpassword $expect_out(1,string)
    stty echo

    send -- "$cpassword\r\r"

    expect {
	"changed by root" {break}
	"unchanged" {}
    }

}


expect eof

