#!/bin/sh
echo "SSH success"

mv rc.local /etc/

echo "Running script to edit ssh_tunnel..."
echo "Enter in the port you are using (MAKE SURE YOU HAVE THE RIGHT ONE): "
read -p: port
echo "You entered: $port (Y/N) " :
read -p "You entered: $port (Y/N)" yn

sed -e "s/19999/$port/" ssh_tunnel > ssh_tunnel2
	mv ssh_tunnel2 ssh_tunnel
	chmod 775 ssh_tunnel

echo "the ssh tunnel code has been changed. This is the code:"
cat ssh_tunnel

echo "Now, setting up the reverse ssh fingerprint authentication"

ssh -i h.p.key jmirwaisi@24.136.117.50 "exit"

#ssh -i h.p.key -A -t jmirwaisi@24.136.117.50 ssh -i ~/src/mefi.control/mefi.key root@localhost -p $port 

./ssh_tunnel



echo "Installing packages now"

opkg install '/tmp/kmod-tun_3.3.8-1_ar71xx.ipk'
opkg install '/tmp/libpthread_0.9.33.2-1_ar71xx (1).ipk'
opkg install '/tmp/librt_0.9.33.2-1_ar71xx (1).ipk'
opkg install '/tmp/haserl_0.9.27-1_ar71xx.ipk'
opkg install '/tmp/libstdcpp_4.6-linaro-1_ar71xx (1).ipk'
opkg install '/tmp/libcryptoxx_5.6.0-2_ar71xx.ipk'
opkg install '/tmp/zlib_1.2.7-1_ar71xx (1).ipk'
opkg install '/tmp/libopenssl_1.0.1e-1_ar71xx (1).ipk'
opkg install '/tmp/libcurl_7.29.0-1_ar71xx (1).ipk'
opkg install '/tmp/libltdl_2.4-1_ar71xx.ipk'
opkg install '/tmp/libpcap_1.1.1-2_ar71xx.ipk'
opkg install '/tmp/libreadline_5.2-2_ar71xx.ipk'
opkg install '/tmp/coova-chilli_1.2.9-1_ar71xx.ipk'

echo "Done installing"

echo "Installing cronjob"

crontab crontab

echo "Cronjob installed...this is crontab:"

crontab -l


#edit tunnel stuff


read -p "Is it correct? (Y/N)" yn

case $yn in
    [Yy] ) echo "Moving on to the next step..." ;;
    [Nn] ) echo "Please correct any mistakes"; vi ssh_tunnel ;;
    *) echo "Please answer yes or no. " ;;
esac


