#!/bin/sh
echo "SSH success"

mv rc.local /etc/

echo "Installing packages now"

opkg install '/tmp/kmod-tun_3.3.8-1_ar71xx.ipk'
opkg install '/tmp/libpthread_0.9.33.2-1_ar71xx (1).ipk'
opkg install '/tmp/librt_0.9.33.2-1_ar71xx (1).ipk'
opkg install '/tmp/haserl_0.9.27-1_ar71xx.ipk'
opkg install '/tmp/libstdcpp_4.6-linaro-1_ar71xx (1).ipk'
opkg install '/tmp/libcryptoxx_5.6.0-2_ar71xx.ipk'
opkg install '/tmp/zlib_1.2.7-1_ar71xx (1).ipk'
opkg install '/tmp/libopenssl_1.0.1e-1_ar71xx (1).ipk'
opkg install '/tmp/libcurl_7.29.0-1_ar71xx (1).ipk'
opkg install '/tmp/libltdl_2.4-1_ar71xx.ipk'
opkg install '/tmp/libpcap_1.1.1-2_ar71xx.ipk'
opkg install '/tmp/libreadline_5.2-2_ar71xx.ipk'
opkg install '/tmp/coova-chilli_1.2.9-1_ar71xx.ipk'

echo "Done installing"

echo "Installing cronjob"

crontab foncron

echo "Cronjob installed...this is crontab:"

crontab -l

echo "Running script to edit ssh_tunnel..."

#edit tunnel stuff
./edit_tun
#edit tunnel stuff
echo "Now, setting up the reverse ssh fingerprint authentication"

ssh jmirwaisi@24.136.117.50 -i h.p.key "exit"

./ssh_tunnel



