#!/bin/sh

echo "Enter in the port you are using (MAKE SURE YOU HAVE THE RIGHT ONE): "
read -p: port
echo "You entered: $port (Y/N) " :
read -p "You entered: $port (Y/N)" yn

sed -e "s/19999/$port/" ssh_tunnel > ssh_tunnel2
	mv ssh_tunnel2 ssh_tunnel
	chmod 775 ssh_tunnel

echo "the ssh tunnel code has been changed. This is the code:"
cat ssh_tunnel

read -p "Is it correct? (Y/N)" yn

case $yn in
    [Yy] ) echo "Moving on to the next step..." ;;
    [Nn] ) echo "Please correct any mistakes"; vi ssh_tunnel ;;
    *) echo "Please answer yes or no. " ;;
esac
